In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [2]:
def selsectkbest(indep_X,dep_Y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fift1=test.fift(indep_X,dep_Y)
    selectk_featuer= fit1.transform(indep_X)
    return selsectbest_features

In [3]:
def split_scalar(indep_X,dep_Y):
    X_train,X_test,y_train,y_test=train_test_split(indep_X,dep_Y,test_size=0.20,random_state=0)
    sc=StandardScaler()
    X_train=sc.fit_transform(X_train)
    X_test=sc.transform(X_test)
    return X_train,X_test,y_test,y_train

In [4]:
def r2_prediction(regressor,X_test,y_teast):
    y_pred= regressor.predict(X_test)
    from sklearn.metrics import r2_score
    r2=r2_score(y_test,y_pred)
    return r2

In [5]:
def Linear (X_train,y_train,X_test):
    from sklearn.linear_model import LinearRegression
    regressor=LinearRegression()
    regressor.fit(X_train,y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return r2

In [6]:
def svm_Linear (X_train,y_train,X_test):
    from sklearn.svm_model import SVR
    regressor=SVR(kernel='linear')
    regressor.fit(X_train,y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return r2

In [7]:
def svm_NL (X_train,y_train,X_test):
    from sklearn.svm_model import SVR
    regressor=SVR(kernel='rbf')
    regressor.fit(X_train,y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return r2

In [8]:
def Decision (X_train,y_train,X_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor=DecisionTreeRegressor(criterion='squared_error', splitter='best',max_features='sqrt',random_state=0)
    regressor.fit(X_train,y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return r2

In [9]:
def random (X_train,y_train,X_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor=RandomForestRegressor(n_estimators=100,random_state=0)
    regressor.fit(X_train,y_train)
    r2=r2_prediction(regressor,X_test,y_test)
    return r2

In [10]:
def Selectk_regression(acclin,accsvmnl,accdes,accrf):
    dataframe=pd.dataFrame(index=['ChiSquare'],colums=['Linear','SVMl','SVMnl','Decision','Random'])
    for number ,idex in enumerate(dataframe.index):
        dataframe['Linear'][index]=acclin[number]
        dataframe['SVM1'][index]=accsvmnl[number]
        dataframe['SVMnl'][index][number]
        dataframe['Decision'][index][number]
        dataframe['Random'][index][number]

In [11]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2=pd.get_dummies(df2,drop_first=True)
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [17]:
kbest=selsectkbest(indep_X,dep_Y,5)
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

NameError: name 'indep_X' is not defined