In [18]:
# Importing the libraries
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
import pickle
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [19]:
# Applying PCA
def pca (indep_X,n):
    pca = PCA(n_components = 2)
    X_train = pca.fit_transform(indep_X)
    X_test = pca.transform(indep_X)
    explained_variance = pca.explained_variance_ratio_
    return X_test

In [20]:
def split_scalar(indep_X,dep_Y):
    X_train,X_test,y_train,y_test=train_test_split(indep_X,dep_Y, test_size=0.25,random_state=0)
    sc=StandardScaler()
    X_train=sc.fit_transform(X_train)
    X_test=sc.fit_transform(X_test)
    return X_train,X_test,y_train,y_test

In [21]:
def cm_prediction(classifier,X_test):
    y_pred=classifier.predict(X_test)
    # Making the Confusion Matrix
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score
    from sklearn.metrics import classification_report
    Accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,Accuracy,report,X_test,y_test,cm

In [22]:
# Aboue as  the cm Same to the all model runing
def logistic(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.linear_model import LogisticRegression
    classifier =LogisticRegression(random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [23]:
def svm_linear(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.svm import SVC
    classifier =SVC(kernel = 'linear',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [24]:

def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='rbf', gamma='scale',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [25]:
def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier=GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [26]:
def knn(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.neighbors import KNeighborsClassifier
    classifier=KNeighborsClassifier(n_neighbors=7,weights='uniform',algorithm='auto',leaf_size=30,p=2,metric='minkowski')
    classifier.fit(X_train,y_train)
    classifier,Accuraacy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [27]:
def DecisionTree(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion='entropy', splitter='random',max_features='sqrt',random_state=0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [28]:
def RandomForest(X_train,y_train,X_test):
     # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators = 10, criterion = 'entropy',max_features='sqrt', random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [29]:
# all model of the same table create are created to funcation
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe # return to the funcation to dataframe

In [30]:
dataset1=pd.read_csv('prep.csv',index_col=None)
df2=dataset1 # back up of the original dataset
df2=pd.get_dummies(df2,drop_first=True)
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,False,False,False,False,False,True,False,False,True
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,False,False,True,True,False,True,False,True,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,False,False,True,True,False,False,False,False,True
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,False,False,True,True,False,True,False,True,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,False,False,False,False,False,True,False,False,False

In [31]:
# independent and dependent variables suppurating to the funcation
indep_X = df2.drop(['classification_yes'], axis=1)
dep_Y = df2['classification_yes']

In [35]:
# Call the k-best independent department x, y to create an accuracy list using the provided parameters and set k = n.
PCA=pca(indep_X,6)
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]
PCA

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
X_train,X_test,y_train,y_test=split_scalar(PCA,dep_Y)
#  The funcation call to the appends to the accuracy same to the another model
classification,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classification,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)
accsvml.append(Accuracy)

classification,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)
accsvmnl.append(Accuracy)

classification,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)
accnav.append(Accuracy)

classification,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)
accknn.append(Accuracy)

classification,Accuracy,report,X_test,y_test,cm=DecisionTree(X_train,y_train,X_test)
accdes.append(Accuracy)

classification,Accuracy,report,X_test,y_test,cm=RandomForest(X_train,y_train,X_test)
accrf.append(Accuracy)
# The All list input and create the table in the run function
result=selectk_Classification(acclog,accsvml,accsvmnl,accnav,accknn,accdes,accrf)

In [34]:
#4
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
PCA     0.73  0.74  0.75  0.76  0.76     0.65   0.68

In [17]:
# 5
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
PCA     0.73  0.74  0.75  0.76  0.76     0.65   0.68

In [36]:
#6
result

    Logistic  SVMl SVMnl   KNN Navie Decision Random
PCA     0.73  0.74  0.75  0.76  0.76     0.65   0.68